### ISSUE TITLE
Fetch USA Office of Foreign Assets Control - Non-SDN Lists

### ISSUE THREAD

**Issue by clariechek** [amlcloud/sanctions#8]
https://home.treasury.gov/policy-issues/office-of-foreign-assets-control-sanctions-programs-and-information

https://www.treasury.gov/ofac/downloads/consolidated/cons_add.csv

**Comment by serge-ivo** [comment]
Let's put it on hold while Aishwarya fixes this ticket

**Comment by aishsmanian** [comment]
The csv/ del files are separately maintained for Primary Names, Alternate Names and Addresses.

this consolidated XML file holds all information together - updated register  -
 https://www.treasury.gov/ofac/downloads/consolidated/consolidated.xml
